# Generated by Django 5.2 on 2025-04-26 20:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chatbot',
            fields=[
                ('chatbot_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='New Chatbot', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('prompt', models.TextField(blank=True, null=True)),
                ('llm_provider', models.CharField(choices=[('openai', 'OpenAI'), ('google', 'Google'), ('deepseek', 'DeepSeek')], default='openai', max_length=255)),
                ('llm_model', models.CharField(choices=[('gpt-4o-mini', 'GPT-4o Mini'), ('gpt-4o', 'GPT-4o'), ('gpt-4', 'GPT-4'), ('gpt-3.5-turbo', 'GPT-3.5 Turbo'), ('gemini-1.5-pro-latest', 'Gemini 1.5 Pro'), ('deepseek-chat', 'DeepSeek Chat')], default='gpt-4o-mini', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('channel_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel_type', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('messenger', 'Messenger'), ('sms', 'SMS'), ('email', 'Email'), ('web', 'Web Chat')], max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chatbot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.chatbot')),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('conversation_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_number', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.channel')),
                ('chatbot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.chatbot')),
            ],
        ),
        migrations.CreateModel(
            name='EmailChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=254)),
                ('provider', models.CharField(choices=[('gmail', 'Gmail'), ('outlook', 'Outlook'), ('imap', 'IMAP'), ('smtp', 'SMTP Custom')], max_length=100)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('smtp_server', models.CharField(blank=True, max_length=255, null=True)),
                ('smtp_port', models.CharField(blank=True, max_length=255, null=True)),
                ('imap_server', models.CharField(blank=True, max_length=255, null=True)),
                ('imap_port', models.CharField(blank=True, max_length=255, null=True)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('watch_expiration', models.DateTimeField(blank=True, null=True)),
                ('watch_history_id', models.CharField(blank=True, max_length=255, null=True)),
                ('channel', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_config', to='chat.channel')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True, null=True)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.conversation')),
            ],
        ),
        migrations.CreateModel(
            name='MessengerChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.CharField(blank=True, max_length=255, null=True)),
                ('page_name', models.CharField(blank=True, max_length=255, null=True)),
                ('access_token', models.TextField(blank=True, null=True)),
                ('channel', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messenger_config', to='chat.channel')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=255, unique=True)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.channel')),
            ],
        ),
        migrations.CreateModel(
            name='WhatsAppChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twilio_account_sid', models.CharField(blank=True, max_length=255, null=True)),
                ('twilio_auth_token', models.CharField(blank=True, max_length=255, null=True)),
                ('twilio_phone_number', models.CharField(blank=True, max_length=255, null=True)),
                ('channel', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_config', to='chat.channel')),
            ],
        ),
    ]
