# Generated by Django 5.2 on 2025-04-27 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='from_email',
            field=models.CharField(default='kashifmehmood926@gmail.com', max_length=255),
            preserve_default=False,
        ),
    ]
