# Generated by Django 5.2 on 2025-04-27 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_conversation_from_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailchannel',
            name='access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emailchannel',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
