# Generated by Django 5.2 on 2025-04-18 19:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='llm_model',
            field=models.CharField(choices=[('gpt-4o-mini', 'GPT-4o Mini'), ('gpt-4o', 'GPT-4o'), ('gpt-4', 'GPT-4'), ('gpt-3.5-turbo', 'GPT-3.5 Turbo'), ('gemini-1.5-pro-latest', 'Gemini 1.5 Pro'), ('deepseek-chat', 'DeepSeek Chat')], default='gpt-4o-mini', max_length=255),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='llm_provider',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('google', 'Google'), ('deepseek', 'DeepSeek')], default='openai', max_length=255),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='name',
            field=models.CharField(default='New Chatbot', max_length=255),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('channel_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel_type', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('messenger', 'Messenger'), ('sms', 'SMS'), ('email', 'Email'), ('web', 'Web Chat')], max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chatbot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.chatbot')),
            ],
        ),
        migrations.AddField(
            model_name='conversation',
            name='channel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chat.channel'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='EmailChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=254)),
                ('provider', models.CharField(choices=[('gmail', 'Gmail'), ('outlook', 'Outlook'), ('imap', 'IMAP'), ('smtp', 'SMTP Custom')], max_length=100)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('smtp_server', models.CharField(blank=True, max_length=255, null=True)),
                ('smtp_port', models.IntegerField(blank=True, null=True)),
                ('imap_server', models.CharField(blank=True, max_length=255, null=True)),
                ('imap_port', models.IntegerField(blank=True, null=True)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('channel', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_config', to='chat.channel')),
            ],
        ),
        migrations.CreateModel(
            name='MessengerChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.CharField(blank=True, max_length=255, null=True)),
                ('page_name', models.CharField(blank=True, max_length=255, null=True)),
                ('access_token', models.TextField(blank=True, null=True)),
                ('channel', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messenger_config', to='chat.channel')),
            ],
        ),
        migrations.CreateModel(
            name='WhatsAppChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twilio_account_sid', models.CharField(blank=True, max_length=255, null=True)),
                ('twilio_auth_token', models.CharField(blank=True, max_length=255, null=True)),
                ('twilio_phone_number', models.CharField(blank=True, max_length=255, null=True)),
                ('channel', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_config', to='chat.channel')),
            ],
        ),
    ]
