# Generated by Django 5.2 on 2025-04-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatbot_is_active_chatbot_is_public_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailchannel',
            name='imap_port',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='emailchannel',
            name='smtp_port',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
