# Generated by Django 5.2 on 2025-05-14 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_emailchannel_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='session_key',
            field=models.CharField(default=13124, max_length=255),
            preserve_default=False,
        ),
    ]
