# Generated by Django 5.2 on 2025-04-24 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_emailchannel_imap_port_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='chatbot',
        ),
        migrations.RemoveField(
            model_name='message',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='message',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], default='user', max_length=255),
            preserve_default=False,
        ),
    ]
