# Generated by Django 5.2 on 2025-04-26 20:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('knowledge_base_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chatbot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.chatbot')),
            ],
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, null=True)),
                ('file', models.FileField(blank=True, upload_to='data_sources/')),
                ('text_title', models.CharField(max_length=200)),
                ('text_content', models.TextField()),
                ('source_type', models.CharField(choices=[('url', 'URL'), ('file', 'File'), ('text', 'Text')], max_length=200)),
                ('chunk_ids', models.JSONField(blank=True, default=list, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kb.knowledgebase')),
            ],
        ),
    ]
