# Generated by Django 5.2 on 2025-04-24 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='chunk_ids',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
